name: localline
description: offline chat
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Bluetooth Low Energy
  flutter_blue_plus: ^1.31.12

  # SQLite für Nachrichten-Speicherung
  sqflite: ^2.3.0
  path: ^1.9.0

  # UI und Utils
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1